# Setup
title: Not Pure Poole
description: A simple, beautiful, and powerful Jekyll theme for blogs
url: https://vszhub.github.io
paginate: 1
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Songzi Vong
  url: https://github.com/vszhub/
  email: vszhub@gmail.com

# Custom vars
version: 0.1.0
